title: Aly Saleh
description: Aly Saleh Website
url: salehaly.github.io
author: Aly Saleh
twitter: 
  username: alysaaleh
  card: summary
social:
  name: Aly Saleh
  links:
    - https://twitter.com/alysaaleh
    - https://www.linkedin.com/in/aly-saleh-ba948164
    - https://github.com/salehaly


plugins:
  - jekyll-seo-tag
